# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployplan',
            name='auth_key',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
